version: "3"

services:
  ###########################################
  # Use Makefile to deploy Hadoop with YARN #
  ###########################################

  #######
  # DFS #
  #######
  namenode:
    image: bde2020/hadoop-namenode:1.2.0-hadoop2.7.4-java8
    networks:
      - hbase
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    ports:
      - "50070:50070"
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:1.2.0-hadoop2.7.4-java8
    networks:
      - hbase
    depends_on:
      - namenode
    volumes:
      - datanode1:/hadoop/dfs/data
    ports:
      - "50075:50075"
    env_file:
      - ./hadoop.env

  ########
  # YARN #
  ########

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:1.2.0-hadoop2.7.4-java8
    networks:
      - hbase
    ports:
      - "8088:8088"
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: bde2020/hadoop-nodemanager:1.2.0-hadoop2.7.4-java8
    networks:
      - hbase
    ports:
      - "8042:8042"
    env_file:
      - ./hadoop.env

  historyserver:
    image: bde2020/hadoop-historyserver:1.2.0-hadoop2.7.4-java8
    networks:
      - hbase
    volumes:
      - historyserver:/hadoop/yarn/timeline
    ports:
      - "8188:8188"
    env_file:
      - ./hadoop.env

volumes:
  historyserver:
  namenode:
  datanode1:


networks:
  hbase:
    external: true
